const content = {
    dashboard:"Dashboard",
    teamManage:"Team Managements",
    teamContact:"Team contacts",
    storyBook:"Story Book",
    dashlink:"/dashboard",
    teamcontactlink:"/teamContact",
    teamManagelink:"/teamManagements",
    storylink:"/storyBook",
    button:"Button Components",
    button1:"Default Buttons",
    button2:"Buttons With Icon",
    dropdown:"DropDown Components",
    dropdown1:"Default Dropdown",
    dropdown2:"DropDown With Error",
    dropdown3:"Multi-Select Dropdown",
    card:"Cards Components",
    input:"Input Controls Component",
    input1:"Textarea",
    input2:"Input-field",
    input3:"Search Box",
    layout:"Layout Controls",
    layout1:"Header",
    layout2:"Footer",
    layout3:"Left Navigation",
    table:"Table Component",
    grid:"Grid Control Component",
    grid1:"Default Grid",
    grid2:"Grid With Scroll",
    grid3:"Grid With Pagination",
    grid4:"Grid With Action",
    grid5:"Grid With Colorcode",
    pagination:"Pagination Component",
    carousel:"Carousels Component",
    modal:"Modal PopUp Component",
    utility:"Utilities",
    utility1:"Headings",
    utility2:"Labels",
    utility3:"Icons",
    layoutcontrol:"Layout Controls",
    layoutcontrol1:"Layout Control - Side Navigationbar",
    email:"Group Email",
    annouce:"Announcements",
    task:"Tasks",
    buttonlink:"./default-button.html",
    buttonlink1:"./button-with-icon.html",
    ddlink:"./default-dropdown.html",
    ddlink1:"./dropdown-with-error.html",
    ddlink2:"./multi-select-dropdown.html",
    clink:"cardscomponent.html",
    pagelink:"paginationcomponent.html",
    carolink:"./carouselscomponent.html",
    modallink:"modalpopupcomponent.html",
    tablelink:"tablecomponent.html",
    inputlink:"./textarea.html",
    inputlink1:"./input.html",
    inputlink2:"./search-box.html",
    laylink:"layout-header.html",
    laylink1:"layout-footer.html",
    laylink2:"layout-leftnavigation.html",
    gridlink:"./default-grid.html",
    gridlink1:"./gridwithscroll.html",
    gridlink2:"./gridwithpagination.html",
    gridlink3:"./gridwithactions.html",
    gridlink4:"./gridwithcolorcoding.html",
    Uheading:"headings.html",
    Ulabels:"labels.html",
    Uicons:"icons.html",
    footerText:"Copyrights have been reserved for this page",
    layoutHeading:"Layout Control",
    layoutHeading2:"Layout Control - Side Navigationbar",
    groupEmail:"Group Email",
    AnnouncementsText:"Announcements",
    TasksText:"Tasks",
    

}
export default content
